image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/J1Z5GI992Z4ESWW9sQDiROyfrtjtCiwhC6K1yZAB6FY.html ./public/.well-known/acme-challenge/J1Z5GI992Z4ESWW9sQDiROyfrtjtCiwhC6K1yZAB6FY
  artifacts:
    paths:
    - public
  only:
  - master
