image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/TacLyRp7iV6hkv8zGTu67AvwlkpDx6TQK8u8z6Fry5g.html ./public/.well-known/acme-challenge/TacLyRp7iV6hkv8zGTu67AvwlkpDx6TQK8u8z6Fry5g
  artifacts:
    paths:
    - public
  only:
  - master
