image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/pXpDJMGp9rr9oK4gwcA_qpEfHf6pby8aFHYmSFG_R7c.html ./public/.well-known/acme-challenge/pXpDJMGp9rr9oK4gwcA_qpEfHf6pby8aFHYmSFG_R7c
  artifacts:
    paths:
    - public
  only:
  - master
