# Site
title:              Influencing Machine
bio:                'INFLUENCING MACHINE is a Nottingham-based collective and production company, specialising in new writing.'
description:        "INFLUENCING MACHINE is a Nottingham-based collective and production company, specialising in new writing."
locale:             en_UK
url:                "/" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         /assets/sass
  style:            compressed

# Comments
disqus_shortname:   influencing-machine

# Social
analytics-id:       "default"
twitter:            "I_M_prod"
facebook:           "influencing.machine"

# personal
location:           Nottingham, UK
phone:              +44 7795203082
email:              hugh@hugh-dichmont.com

# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
